name: nvfbcwrp

on: workflow_dispatch

env:
  SOLUTION_FILE_PATH: win\nvfbcwrp\nvfbcwrp.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - uses: microsoft/setup-msbuild@v2

    - working-directory: "${{github.workspace}}"
      run: nuget restore "${{env.SOLUTION_FILE_PATH}}"

    - working-directory: "${{github.workspace}}"
      shell: cmd
      run: |
        REM MSBuild -m -p:"Configuration=${{env.BUILD_CONFIGURATION}};Platform=x64" "${{env.SOLUTION_FILE_PATH}}"
        MSBuild -m -p:Configuration="${{env.BUILD_CONFIGURATION}}" -p:Platform="x64" "${{env.SOLUTION_FILE_PATH}}"

    - working-directory: "${{github.workspace}}"
      shell: cmd
      run: |
        REM MSBuild -m -p:"Configuration=${{env.BUILD_CONFIGURATION}};Platform=x86" "${{env.SOLUTION_FILE_PATH}}"
        MSBuild -m -p:Configuration="${{env.BUILD_CONFIGURATION}}" -p:Platform="x86" "${{env.SOLUTION_FILE_PATH}}"

    - uses: actions/upload-artifact@v4
      with:
        path: "${{github.workspace}}"
